parameters:

    # Database Settings
    database_name: training_todo
    database_host: localhost
    database_user: root
    database_pass: null
    database_port: 3306

    # Application Settings
    exception_handler:   'Todo\Controller\ExceptionController::exceptionAction'

    # Twig Configuration
    templating.options:
        debug:            %kernel.debug%
        strict_variables: %kernel.debug%
        cache:            %kernel.cache_dir%/twig

    templating_loader.paths: [ %kernel.views_dir% ]

    # Routing Configuration
    file_locator.paths:   [ %kernel.config_dir% ]

    router_file:          %kernel.config_dir%/routes.yml
    router.options:
        cache_dir:        %kernel.cache_dir%
        debug:            %kernel.debug%
