homepage:
    path:        /
    defaults:    { _controller: Todo\Controller\TodoController::indexAction }
    methods:     GET

todo_create:
    path:         /create
    defaults:     { _controller: Todo\Controller\TodoController::createAction }
    methods:      POST

todo_close:
    path:         /todo/{id}/close
    defaults:     { _controller: Todo\Controller\TodoController::closeAction }
    requirements: { id: \d+ }
    methods:      GET

todo_delete:
    path:         /todo/{id}/delete
    defaults:     { _controller: Todo\Controller\TodoController::deleteAction }
    requirements: { id: \d+ }
    methods:      GET

todo_show:
    path:         /todo/{id}
    defaults:     { _controller: Todo\Controller\TodoController::todoAction }
    requirements: { id: \d+ }
    methods:      GET
