homepage:
    path:     /
    defaults: { _controller: Todo\Controller\TodoController::indexAction, foo: bar }
    methods:  GET

todo_list:
    path:     /list.php
    defaults: { script: list }
    methods:  [ GET, POST ]

todo_show:
    path:     /todo.php
    defaults: { script: todo }
    methods:  GET
