imports:
    - { resource: parameters.yml }

services:
    twig.asset_extension:
        class:     Todo\Twig\AssetExtension
        arguments: [ @request_stack ]

    twig.routing_extension:
        class:     Todo\Twig\RoutingExtension
        arguments: [ @router ]

    controller_listener:
        class:     Todo\EventListener\ControllerListener
        arguments: [ @service_container ]

    exception_listener:
        class:     Symfony\Component\HttpKernel\EventListener\ExceptionListener
        arguments: [ '%exception_handler%' ]

    router_listener:
        class:     Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments: [ @router, @request_context, null, @request_stack ]

    request_stack:
        class:     Symfony\Component\HttpFoundation\RequestStack

    request_context:
        class:     Symfony\Component\Routing\RequestContext

    yaml_file_loader:
        class:     Symfony\Component\Routing\Loader\YamlFileLoader
        arguments: [ @file_locator ]

    file_locator:
        class:     Symfony\Component\Config\FileLocator
        arguments: [ '%file_locator.paths%' ]

    router:
        class:     Symfony\Component\Routing\Router
        arguments: [ @yaml_file_loader, '%router_file%', '%router.options%', @request_context ]

    event_dispatcher:
        class:     Symfony\Component\EventDispatcher\EventDispatcher
        calls:
            -      [ addSubscriber, [ @router_listener ] ]
            -      [ addSubscriber, [ @exception_listener ] ]
            -      [ addSubscriber, [ @controller_listener ] ]

    templating_loader:
        class:     Twig_Loader_Filesystem
        arguments: [ '%templating_loader.paths%' ]
        public:    false

    templating:
        class:     Twig_Environment
        arguments: [ @templating_loader, '%templating.options%' ]
        calls:
            -      [ addExtension, [ @twig.routing_extension ] ]
            -      [ addExtension, [ @twig.asset_extension ] ]

    http_kernel:
        class:     Symfony\Component\HttpKernel\HttpKernel
        arguments: [ @event_dispatcher, @controller_resolver, @request_stack ]

    database_connection:
        class:     Database\Connection
        arguments: [ %database_name%, %database_user%, %database_pass%, %database_host%, %database_port% ]

    todo_gateway:
        class:     Todo\Model\TodoGateway
        arguments: [ @database_connection ]

    controller_resolver:
        class: Symfony\Component\HttpKernel\Controller\ControllerResolver
